package:
  name: logdate
  version: 1.5.0

source:
  #path: ../../
  git_rev: master
  git_url: https://github.com/uym2/LogDate.git
requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - logdate

about:
  home: https://github.com/uym2/LogDate
  license: GNU GENERAL PUBLIC LICENSE
  license_file: LICENSE
